name: Deploy to GitHub Pages on live branch

# run when a commit is pushed to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the commit that has been pushed
    - uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.143.0'
        extended: true

    - name: Update Hugo Modules
      run: hugo mod tidy

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Node Modules
      run: |
        hugo mod npm pack
        npm install

    - name: Build site
      run: hugo --baseURL "https://brianathans.com" --minify

    # push the generated content into the 'live' branch
    - name: Deploy in live branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: live
        publish_dir: ./public
        cname: brianathans.com
